/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ChatApp {
  export type MessageStruct = {
    sender: AddressLike;
    timestamp: BigNumberish;
    content: string;
    isDeleted: boolean;
    isEdited: boolean;
  };

  export type MessageStructOutput = [
    sender: string,
    timestamp: bigint,
    content: string,
    isDeleted: boolean,
    isEdited: boolean
  ] & {
    sender: string;
    timestamp: bigint;
    content: string;
    isDeleted: boolean;
    isEdited: boolean;
  };
}

export interface ChatAppInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "chatHistory"
      | "deleteMessage"
      | "editMessage"
      | "getChatHistory"
      | "getChatId"
      | "initialize"
      | "owner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "sendMessage"
      | "transferOwnership"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "MessageDeleted"
      | "MessageEdited"
      | "NewMessage"
      | "OwnershipTransferred"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chatHistory",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteMessage",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "editMessage",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChatHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getChatId",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chatHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChatHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChatId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageDeletedEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    index: BigNumberish
  ];
  export type OutputTuple = [sender: string, receiver: string, index: bigint];
  export interface OutputObject {
    sender: string;
    receiver: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageEditedEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    index: BigNumberish,
    newContent: string
  ];
  export type OutputTuple = [
    sender: string,
    receiver: string,
    index: bigint,
    newContent: string
  ];
  export interface OutputObject {
    sender: string;
    receiver: string;
    index: bigint;
    newContent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewMessageEvent {
  export type InputTuple = [
    sender: AddressLike,
    receiver: AddressLike,
    chatId: BytesLike,
    content: string
  ];
  export type OutputTuple = [
    sender: string,
    receiver: string,
    chatId: string,
    content: string
  ];
  export interface OutputObject {
    sender: string;
    receiver: string;
    chatId: string;
    content: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChatApp extends BaseContract {
  connect(runner?: ContractRunner | null): ChatApp;
  waitForDeployment(): Promise<this>;

  interface: ChatAppInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  chatHistory: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, string, boolean, boolean] & {
        sender: string;
        timestamp: bigint;
        content: string;
        isDeleted: boolean;
        isEdited: boolean;
      }
    ],
    "view"
  >;

  deleteMessage: TypedContractMethod<
    [partner: AddressLike, index: BigNumberish],
    [void],
    "nonpayable"
  >;

  editMessage: TypedContractMethod<
    [partner: AddressLike, index: BigNumberish, newContent: string],
    [void],
    "nonpayable"
  >;

  getChatHistory: TypedContractMethod<
    [partnerAddress: AddressLike],
    [ChatApp.MessageStructOutput[]],
    "view"
  >;

  getChatId: TypedContractMethod<
    [userA: AddressLike, userB: AddressLike],
    [string],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendMessage: TypedContractMethod<
    [receiver: AddressLike, content: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "chatHistory"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, string, boolean, boolean] & {
        sender: string;
        timestamp: bigint;
        content: string;
        isDeleted: boolean;
        isEdited: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deleteMessage"
  ): TypedContractMethod<
    [partner: AddressLike, index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "editMessage"
  ): TypedContractMethod<
    [partner: AddressLike, index: BigNumberish, newContent: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getChatHistory"
  ): TypedContractMethod<
    [partnerAddress: AddressLike],
    [ChatApp.MessageStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChatId"
  ): TypedContractMethod<
    [userA: AddressLike, userB: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [receiver: AddressLike, content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MessageDeleted"
  ): TypedContractEvent<
    MessageDeletedEvent.InputTuple,
    MessageDeletedEvent.OutputTuple,
    MessageDeletedEvent.OutputObject
  >;
  getEvent(
    key: "MessageEdited"
  ): TypedContractEvent<
    MessageEditedEvent.InputTuple,
    MessageEditedEvent.OutputTuple,
    MessageEditedEvent.OutputObject
  >;
  getEvent(
    key: "NewMessage"
  ): TypedContractEvent<
    NewMessageEvent.InputTuple,
    NewMessageEvent.OutputTuple,
    NewMessageEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MessageDeleted(address,address,uint256)": TypedContractEvent<
      MessageDeletedEvent.InputTuple,
      MessageDeletedEvent.OutputTuple,
      MessageDeletedEvent.OutputObject
    >;
    MessageDeleted: TypedContractEvent<
      MessageDeletedEvent.InputTuple,
      MessageDeletedEvent.OutputTuple,
      MessageDeletedEvent.OutputObject
    >;

    "MessageEdited(address,address,uint256,string)": TypedContractEvent<
      MessageEditedEvent.InputTuple,
      MessageEditedEvent.OutputTuple,
      MessageEditedEvent.OutputObject
    >;
    MessageEdited: TypedContractEvent<
      MessageEditedEvent.InputTuple,
      MessageEditedEvent.OutputTuple,
      MessageEditedEvent.OutputObject
    >;

    "NewMessage(address,address,bytes32,string)": TypedContractEvent<
      NewMessageEvent.InputTuple,
      NewMessageEvent.OutputTuple,
      NewMessageEvent.OutputObject
    >;
    NewMessage: TypedContractEvent<
      NewMessageEvent.InputTuple,
      NewMessageEvent.OutputTuple,
      NewMessageEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
